pool: "Default"

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - '*'

pr: none

variables:
  - group: kw-nexus-reader
  - name: main_repository_name
    value: 'drupalwiki_r2r_hatchet'

resources:
  repositories:
    - repository: dockerfile_library
      type: github
      name: KontextWork/dockerfile_library
      ref: master
      endpoint: KontextWork
    - repository: azureCommonTemplates
      type: github
      name: KontextWork/azure-common-templates
      ref: master
      endpoint: KontextWork

jobs:
  - job: docker_image
    displayName: Release services
    dependsOn: []
    steps:
    - checkout: self
      fetchDepth: 5
    - checkout: dockerfile_library
      fetchDepth: 1
    - template: action/git/version_from_tag.yml@azureCommonTemplates
    - template: action/git/find_best_branch_name.yml@azureCommonTemplates
    ##### hatchet ###############################
    - template: action/docker/build-image.yml@azureCommonTemplates
      parameters:
        main_repository_name: $(main_repository_name)
        dockerfile_basepath_relative: 'docker/hatchet'
        docker_image_name: 'rag/r2r/hatchet-admin'
        dockerfile_filename: 'Dockerfile_admin'
        docker_image_tag: $(releaseVersion)
        docker_image_registry_domain: updates.drupal-wiki.com
        vsc_commit_hash: $(Build.SourceVersion)
        vsc_branch: $(best_branch_name_long)
        ci_build_number: $(Build.BuildNumber)
        docker_image_registry_endpoint: "dw_production_docker_registry"
    - template: action/docker/build-image.yml@azureCommonTemplates
      parameters:
        main_repository_name: $(main_repository_name)
        dockerfile_basepath_relative:  'docker/hatchet'
        docker_image_name: 'rag/r2r/hatchet-dashboard'
        dockerfile_filename: 'Dockerfile_dashboard'
        docker_image_tag: $(releaseVersion)
        docker_image_registry_domain: updates.drupal-wiki.com
        vsc_commit_hash: $(Build.SourceVersion)
        vsc_branch: $(best_branch_name_long)
        ci_build_number: $(Build.BuildNumber)
        docker_image_registry_endpoint: "dw_production_docker_registry"
    - template: action/docker/build-image.yml@azureCommonTemplates
      parameters:
        main_repository_name: $(main_repository_name)
        dockerfile_basepath_relative:  'docker/hatchet'
        docker_image_name: 'rag/r2r/hatchet-engine'
        dockerfile_filename: 'Dockerfile_engine'
        docker_image_tag: $(releaseVersion)
        docker_image_registry_domain: updates.drupal-wiki.com
        vsc_commit_hash: $(Build.SourceVersion)
        vsc_branch: $(best_branch_name_long)
        ci_build_number: $(Build.BuildNumber)
        docker_image_registry_endpoint: "dw_production_docker_registry"
    - template: action/docker/build-image.yml@azureCommonTemplates
      parameters:
        main_repository_name: $(main_repository_name)
        dockerfile_basepath_relative: 'docker/hatchet'
        docker_image_name: 'rag/r2r/hatchet-migrate'
        dockerfile_filename: 'Dockerfile_migrate'
        docker_image_tag: $(releaseVersion)
        docker_image_registry_domain: updates.drupal-wiki.com
        vsc_commit_hash: $(Build.SourceVersion)
        vsc_branch: $(best_branch_name_long)
        ci_build_number: $(Build.BuildNumber)
        docker_image_registry_endpoint: "dw_production_docker_registry"
